# Generated by Django 4.0.4 on 2022-06-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_airline_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='img',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
