# Generated by Django 4.0.4 on 2022-06-09 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='flightreservation',
            table='flight_reservations',
        ),
    ]
